const network = [
  {
    netWork: 'ETH',
    chainId: '1',
    symbol: 'ETH',
    decimals: 18,
    gasLimit: 40000,
    rpcUrl: 'https://eth.rpc.blxrbdn.com',
    blockExplorerUrls: 'https://etherscan.io',
    isEvm: true,
  },
  {
    netWork: 'BSC',
    chainId: '56',
    symbol: 'BNB',
    decimals: 18,
    gasLimit: 400000,
    rpcUrl: 'https://bscrpc.com',
    blockExplorerUrls: 'https://bscscan.com',
    isEvm: true,
  },
  {
    netWork: 'HECO',
    chainId: '128',
    symbol: 'HT',
    decimals: 18,
    gasLimit: 400000,
    rpcUrl: 'https://http-mainnet.hecochain.com',
    blockExplorerUrls: 'https://hecoinfo.com',
    isEvm: true,
  },
  {
    netWork: 'POLYGON',
    chainId: '137',
    symbol: 'MATIC',
    decimals: 18,
    gasLimit: 400000,
    rpcUrl: 'https://rpc-mainnet.maticvigil.com/',
    blockExplorerUrls: 'https://polygonscan.com',
    isEvm: true,
  },

  {
    netWork: 'OKExChain',
    chainId: '66',
    symbol: 'OKT',
    decimals: 18,
    gasLimit: 400000,
    rpcUrl: 'https://exchainrpc.okex.org/',
    blockExplorerUrls: 'https://www.oklink.com/okexchain',
    isEvm: true,
  },
  {
    netWork: 'ARB',
    chainId: '42161',
    symbol: 'ETH',
    decimals: 18,
    gasLimit: 400000,
    rpcUrl: 'https://rpc.ankr.com/arbitrum',
    blockExplorerUrls: 'https://arbiscan.io',
    isEvm: true,
  },
  {
    netWork: 'TT',
    chainId: '108',
    symbol: 'TT',
    decimals: 18,
    gasLimit: 400000,
    rpcUrl: 'https://mainnet-rpc.thundercore.com',
    blockExplorerUrls: 'https://scan.thundercore.com',
    isEvm: true,
  },
  {
    netWork: 'FTM',
    chainId: '250',
    symbol: 'FTM',
    decimals: 18,
    gasLimit: 400000,
    rpcUrl: 'https://rpc.ankr.com/fantom',
    blockExplorerUrls: 'https://ftmscan.com',
    isEvm: true,
  },
  {
    netWork: 'AVAXC',
    chainId: '43114',
    symbol: 'AVAX',
    decimals: 18,
    gasLimit: 400000,
    rpcUrl: 'https://api.avax.network/ext/bc/C/rpc',
    blockExplorerUrls: 'https://cchain.explorer.avax.network',
    isEvm: true,
  },
  {
    netWork: 'CELO',
    chainId: '42220',
    symbol: 'CELO',
    decimals: 18,
    gasLimit: 400000,
    rpcUrl: 'https://forno.celo.org',
    blockExplorerUrls: 'https://explorer.celo.org',
    isEvm: true,
  },
  {
    netWork: 'ORC',
    chainId: '58',
    symbol: 'ONG',
    decimals: 18,
    gasLimit: 400000,
    rpcUrl: 'https://dappnode7.ont.io:10339',
    blockExplorerUrls: 'https://explorer.ont.io',
    isEvm: true,
  },
  {
    netWork: 'SGB',
    chainId: '19',
    symbol: 'SGB',
    decimals: 18,
    gasLimit: 40000,
    rpcUrl: 'https://songbird.towolabs.com/rpc',
    blockExplorerUrls: 'https://songbird-explorer.flare.network',
    isEvm: true,
  },
  {
    netWork: 'XDC',
    chainId: '50',
    symbol: 'XDC',
    decimals: 18,
    gasLimit: 400000,
    rpcUrl: 'https://rpc.xinfin.network',
    blockExplorerUrls: 'https://explorer.xinfin.network/',
    isEvm: true,
  },
  {
    netWork: 'KLAY',
    chainId: '8217',
    symbol: 'KLAY',
    decimals: 18,
    gasLimit: 400000,
    rpcUrl: 'https://klaytn.mytokenpocket.vip',
    blockExplorerUrls: 'https://scope.klaytn.com',
    isEvm: true,
  },
  {
    netWork: 'HPB',
    chainId: '269',
    symbol: 'HPB',
    decimals: 18,
    gasLimit: 400000,
    rpcUrl: 'https://hpbnode.com',
    blockExplorerUrls: 'https://hscan.org',
    isEvm: true,
  },
  {
    netWork: 'CRONOS',
    chainId: '25',
    symbol: 'CRO',
    decimals: 18,
    gasLimit: 400000,
    rpcUrl: 'https://evm.cronos.org',
    blockExplorerUrls: 'https://cronos.org/explorer',
    isEvm: true,
  },
  {
    netWork: 'AME',
    chainId: '180',
    symbol: 'AME',
    decimals: 18,
    gasLimit: 400000,
    rpcUrl: 'https://node1.amechain.io/',
    blockExplorerUrls: 'https://amescan.io',
    isEvm: true,
  },
  {
    netWork: 'ECH',
    chainId: '3000',
    symbol: 'ECH',
    decimals: 18,
    gasLimit: 400000,
    rpcUrl: 'https://draco.ech.network',
    blockExplorerUrls: 'https://scout.ech.network',
    isEvm: true,
  },
  {
    netWork: 'CUBE',
    chainId: '1818',
    symbol: 'CUBE',
    decimals: 18,
    gasLimit: 400000,
    rpcUrl: 'https://http-mainnet.cube.network',
    blockExplorerUrls: 'https://www.cubescan.network',
    isEvm: true,
  },
  {
    netWork: 'GNOSIS',
    chainId: '100',
    symbol: 'xDai',
    decimals: 18,
    gasLimit: 400000,
    rpcUrl: 'https://xdai-rpc.gateway.pokt.network',
    blockExplorerUrls: 'https://blockscout.com/poa/xdai',
    isEvm: true,
  },
  {
    netWork: 'ETC',
    chainId: '61',
    symbol: 'ETC',
    decimals: 18,
    gasLimit: 400000,
    rpcUrl: 'https://www.ethercluster.com/etc',
    blockExplorerUrls: 'https://blockscout.com/etc/mainnet',
    isEvm: true,
  },
  {
    netWork: 'KCC',
    chainId: '321',
    symbol: 'KCS',
    decimals: 18,
    gasLimit: 400000,
    rpcUrl: 'https://rpc-mainnet.kcc.network',
    blockExplorerUrls: 'https://explorer.kcc.io/cn',
    isEvm: true,
  },
  {
    netWork: 'BRISE',
    chainId: '32520',
    symbol: 'BRISE',
    decimals: 18,
    gasLimit: 400000,
    rpcUrl: 'https://chainrpc.com',
    blockExplorerUrls: 'https://brisescan.com/',
    isEvm: true,
  },
  {
    netWork: 'ETHF',
    chainId: '513100',
    symbol: 'ETHF',
    decimals: 18,
    gasLimit: 400000,
    rpcUrl: 'https://rpc.etherfair.org',
    blockExplorerUrls: 'https://explorer.etherfair.org',
    isEvm: true,
  },
  {
    netWork: 'ETHW',
    chainId: '10001',
    symbol: 'ETHW',
    decimals: 18,
    gasLimit: 400000,
    rpcUrl: 'https://mainnet.ethereumpow.org',
    blockExplorerUrls: 'https://mainnet.ethwscan.com',
    isEvm: true,
  },
  {
    netWork: 'Optimism',
    chainId: '10',
    symbol: 'ETH',
    decimals: 18,
    gasLimit: 40000,
    rpcUrl: 'https://mainnet.optimism.io',
    blockExplorerUrls: 'https://optimistic.etherscan.io',
    isEvm: true,
  },
  {
    netWork: 'APT',
    chainId: '072611',
    symbol: 'APT',
    blockExplorerUrls: 'https://explorer.aptoslabs.com',
  },
  {
    netWork: 'DRAC',
    chainId: '3912',
    symbol: 'DRAC',
    decimals: 18,
    gasLimit: 40000,
    rpcUrl: ' https://www.dracscan.com/rpc',
    blockExplorerUrls: 'https://www.dracscan.com',
    isEvm: true,
  },
  {
    netWork: 'DC',
    chainId: '2000',
    symbol: 'DOGE',
    decimals: 18,
    gasLimit: 40000,
    rpcUrl: 'https://rpc.dogechain.dog',
    blockExplorerUrls: 'https://explorer.dogechain.dog',
    isEvm: true,
  },
  {
    netWork: 'FSC',
    chainId: '201022',
    symbol: 'FON',
    decimals: 18,
    gasLimit: 40000,
    rpcUrl: 'https://fsc-dataseed1.fonscan.io',
    blockExplorerUrls: 'https://fonscan.io',
    isEvm: true,
  },
  {
    netWork: 'FRZ',
    chainId: '1995',
    symbol: 'FRZ',
    decimals: 18,
    gasLimit: 40000,
    rpcUrl: 'https://mainnet.frzchain.com',
    blockExplorerUrls: 'https://explorer.frzchain.com',
    isEvm: true,
  },
  {
    netWork: 'GRC30',
    chainId: '8192',
    symbol: 'GPB',
    decimals: 18,
    gasLimit: 40000,
    rpcUrl: 'https://galaxypc.org',
    blockExplorerUrls: 'https://browser.galaxypc.vip/home',
    isEvm: true,
  },
  {
    netWork: 'CORE',
    chainId: '1116',
    symbol: 'CORE',
    decimals: 18,
    gasLimit: 40000,
    rpcUrl: 'https://rpc.coredao.org',
    blockExplorerUrls: 'https://scan.coredao.org',
    isEvm: true,
  },
  {
    netWork: 'MTR',
    chainId: '82',
    symbol: 'MTR',
    decimals: 18,
    gasLimit: 40000,
    rpcUrl: 'https://rpc.meter.io',
    blockExplorerUrls: 'https://scan.meter.io',
    isEvm: true,
  },
  {
    netWork: 'BTTC',
    chainId: '199',
    symbol: 'BTT',
    decimals: 18,
    gasLimit: 40000,
    rpcUrl: 'https: //rpc.bt.io',
    blockExplorerUrls: 'https://bttcscan.com',
    isEvm: true,
  },
  {
    netWork: 'ZKSYNC',
    chainId: '324',
    symbol: 'ETH',
    decimals: 18,
    gasLimit: 40000,
    rpcUrl: 'https://zksync2-mainnet.zksync.io',
    blockExplorerUrls: 'https://explorer.zksync.io',
    isEvm: true,
  },
  {
    netWork: 'CFX',
    chainId: '1030',
    symbol: 'CFX',
    decimals: 18,
    gasLimit: 40000,
    rpcUrl: 'https://evm.confluxrpc.com',
    blockExplorerUrls: 'https://evm.confluxscan.net',
    isEvm: true,
  },
  {
    netWork: 'FVM',
    chainId: '314',
    symbol: 'FIL',
    decimals: 18,
    gasLimit: 40000,
    rpcUrl: 'https://rpc.ankr.com/filecoin',
    blockExplorerUrls: 'https://filfox.info/en',
    isEvm: true,
  },
  {
    netWork: 'EOS(EVM)',
    chainId: '17777',
    symbol: 'EOS',
    decimals: 18,
    gasLimit: 40000,
    rpcUrl: 'https://api.evm.eosnetwork.com',
    blockExplorerUrls: 'https://explorer.evm.eosnetwork.com',
    isEvm: true,
  },
  {
    netWork: 'SUI',
    chainId: '7299',
    symbol: 'SUI',
    decimals: 9,
    blockExplorerUrls: 'https://explorer.sui.io',
    isEvm: true,
  },
  {
    netWork: 'PulseChain',
    chainId: '369',
    symbol: 'PLS',
    decimals: 18,
    gasLimit: 40000,
    rpcUrl: 'https://rpc.pulsechain.com',
    blockExplorerUrls: 'https://otter.pulsechain.com',
    isEvm: true,
  },
  {
    netWork: 'BASE',
    chainId: '8453',
    symbol: 'ETH',
    decimals: 18,
    gasLimit: 40000,
    rpcUrl: 'https://developer-access-mainnet.base.org',
    blockExplorerUrls: 'https://basescan.org',
    isEvm: true,
  },
  {
    netWork: 'LINEA',
    chainId: '59144',
    symbol: 'ETH',
    decimals: 18,
    gasLimit: 40000,
    rpcUrl: 'https://rpc.linea.build',
    blockExplorerUrls: 'https://lineascan.build',
    isEvm: true,
  },
  {
    netWork: 'PEGO',
    chainId: '20201022',
    symbol: 'PG',
    decimals: 18,
    gasLimit: 40000,
    rpcUrl: 'https://pegorpc.com,https://node2.pegorpc.com',
    blockExplorerUrls: 'https://scan.pego.network',
    isEvm: true,
  },
  {
    netWork: 'opBNB',
    chainId: '204',
    symbol: 'BNB',
    decimals: 18,
    gasLimit: 40000,
    rpcUrl: 'https://opbnb-mainnet-rpc.bnbchain.org',
    blockExplorerUrls: 'https://mainnet.opbnbscan.com',
    isEvm: true,
  },
  {
    netWork: 'ETRC20',
    chainId: '8957',
    symbol: 'ETE',
    decimals: 18,
    gasLimit: 40000,
    rpcUrl: 'https://www.etescan.net/rpc',
    blockExplorerUrls: 'https://www.etescan.net/',
    isEvm: true,
  },
  {
    netWork: 'OZO',
    chainId: '4000',
    symbol: 'OZO',
    decimals: 18,
    gasLimit: 40000,
    rpcUrl: 'https://node1.ozonechain.io',
    blockExplorerUrls: 'https://ozonescan.io',
    isEvm: true,
  },
]
export default network 